HW4: Feature/list movies
dpsnow/my-awesome-movie-searcher pull request #2
Opened 2020-01-26 09:00 UTC by dpsnow

2020-01-26 09:25 UTC, kirzharov commented
До проверки нужно вынести из пулл-реквеста #1 все изменения кроме _create-react-app_.

2020-01-26 09:26 UTC, kirzharov requested changes
До проверки нужно вынести из пулл-реквеста #1 все изменения кроме create-react-app.

2020-01-26 12:15 UTC, dpsnow commented
@kirzharov вынесла изменения

2020-01-27 09:55 UTC, Geschoss commented on package.json
> +    "@material-ui/core": "^4.9.0",
воу круто!=)

2020-01-27 09:55 UTC, Geschoss commented on src/movies/item.tsx
> +    const onClickBtnExpand = () => {
Почитай еще про `useCallback` в дальнейшем они понадобятся

2020-01-27 09:55 UTC, Geschoss commented on src/movies/item.tsx
> +    const classes = useStyles();
`const classes = useStyles();` возможно это можно вынести вне компонента, что бы каждый раз не создавать стили

2020-01-27 09:55 UTC, Geschoss commented on src/movies/item.tsx
> +            <CardMedia style={{ height: '300px' }} image={`https://picsum.photos/id/${getRandomInt(500)}/200/300`} />
Нам бы сделать так что бы картинка всегда была одна, а то при нажатии на кнопку идет смена картинки.
Можно попробовать в месте получения данных обойти все элементы и если `poster_path` не заполнен, то генерить url

2020-01-27 09:55 UTC, Geschoss commented on src/movies/list.tsx
> +            fetch('https://devlab.website/v1/movies')
эту url можно вынести в константы
файл `constants.ts`
`const MOVIES_URL = 'https://devlab.website/v1/movies'`

2020-01-27 09:55 UTC, Geschoss commented on src/movies/list.tsx
> +};
Хорошо что ты выносишь логику уже в отдельные функции.
Но тут можно и на месте этот код оставить. Так как он не такой уж большой и не понятный.
Но это не критично

2020-01-27 15:30 UTC, dpsnow commented on src/movies/item.tsx
> +    const classes = useStyles();
не смогла вынести, вываливается ошибка

2020-01-27 15:33 UTC, dpsnow commented on src/movies/item.tsx
> +    const onClickBtnExpand = () => {
почитала про `useCallback`, вроде понятно. Но тут же вроде можно без ?

2020-01-27 15:39 UTC, dpsnow commented on src/movies/item.tsx
> +            <CardMedia style={{ height: '300px' }} image={`https://picsum.photos/id/${getRandomInt(500)}/200/300`} />
добавила fn `replacementPosterPath` в list.tsx

2020-01-27 15:40 UTC, dpsnow commented on src/movies/list.tsx
> +};
перенесла рендер

2020-01-27 15:41 UTC, dpsnow commented on src/movies/list.tsx
> +            fetch('https://devlab.website/v1/movies')
вынесла работу с api в отдельный файл `api.ts`, так как в будущем методом будет больше

2020-02-01 10:53 UTC, Geschoss approved these changes

2020-02-01 10:53 UTC, Geschoss commented on src/movies/list.tsx
> +    const [movies, setMovies] = useState([]);
сюда тоже бы типов добавить

2020-02-03 13:42 UTC, merged